# -*- coding: utf-8 -*-
"""Esercizio_1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g6PZzgkpVGIi2ssViQXRzy6UIri8CN21
"""

#10- Creare un menu ad iserimento che permetta in loop di inserire 
#    un nome e una password e che dopo li verifichi scrivendo "loggato!" 


flag= True

while flag == True:
  x=int(input('scegli cosa fare: 1. esci 2. entra'))
  if x==1:
    flag=False
  elif x==2:
    y=int(input('scegli cosa fare: 3. registrati 4. login'))
    if y==3:
        user_registrazione=input('registrati inserendo il nome utente')
        password_registrazione= input('registrati inserendo la password')
        print('congratulazioni ti sei registrato')
    elif y==4:
        user_login=input('accedi inserendo il nome utente')
        password_login= input('accedi inserendo la password')
        if user_registrazione == user_login and password_registrazione == password_login :
          print('congratulazioni hai effettuato il login con successo')
    else:
        flag=False